name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install bandit

      - name: Run Python File
        run: python app.py

      - name: Run Security Scan
        run: bandit -r . || true

      - name: Send Email Notification
        if: always()
        continue-on-error: true
        run: |
          python - <<EOF
          import smtplib
          from email.mime.text import MIMEText

          try:
              sender = "${{ secrets.EMAIL_USER }}"
              receiver = "${{ secrets.EMAIL_USER }}"
              password = "${{ secrets.EMAIL_PASS }}"

              msg = MIMEText("Code was pushed to repository successfully")
              msg['Subject'] = "CI Alert: Code Changed"
              msg['From'] = sender
              msg['To'] = receiver

              server = smtplib.SMTP('smtp.gmail.com', 587)
              server.starttls()
              server.login(sender, password)
              server.send_message(msg)
              server.quit()

              print("Email sent successfully")

          except Exception as e:
              print("Email failed:", e)
              exit(0)
          EOF